-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 15:00:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema archery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema archery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `archery` DEFAULT CHARACTER SET utf8 ;
USE `archery` ;

-- -----------------------------------------------------
-- Table `archery`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `username_UNIQUE` ON `archery`.`user` (`username` ASC) ;


-- -----------------------------------------------------
-- Table `archery`.`parkour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`parkour` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `countAnimals` INT NOT NULL,
  `countryCode` VARCHAR(3) NOT NULL,
  `city` VARCHAR(75) NOT NULL,
  `street` VARCHAR(75) NOT NULL,
  `zip` VARCHAR(10) NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `archery`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parkourId` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `gamemodeId` INT NOT NULL,
  `userIdCreator` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `event_parkour`
    FOREIGN KEY (`parkourId`)
    REFERENCES `archery`.`parkour` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_user`
    FOREIGN KEY (`userIdCreator`)
    REFERENCES `archery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `id_idx` ON `archery`.`event` (`parkourId` ASC) ;

CREATE INDEX `id_idx1` ON `archery`.`event` (`userIdCreator` ASC) ;


-- -----------------------------------------------------
-- Table `archery`.`eventMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`eventMember` (
  `eventId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`eventId`, `userId`),
  CONSTRAINT `eventMember_event`
    FOREIGN KEY (`eventId`)
    REFERENCES `archery`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `eventMember_user`
    FOREIGN KEY (`userId`)
    REFERENCES `archery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `id_idx` ON `archery`.`eventMember` (`userId` ASC) ;


-- -----------------------------------------------------
-- Table `archery`.`shot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`shot` (
  `id` INT NOT NULL,
  `eventId` INT NOT NULL,
  `userId` INT NOT NULL,
  `animalNumber` INT NOT NULL,
  `shotNumber` INT NOT NULL,
  `points` INT NOT NULL,
  `finished` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `shot_event`
    FOREIGN KEY (`eventId`)
    REFERENCES `archery`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `shot_user`
    FOREIGN KEY (`userId`)
    REFERENCES `archery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `id_idx` ON `archery`.`shot` (`eventId` ASC) ;

CREATE INDEX `id_idx1` ON `archery`.`shot` (`userId` ASC) ;


-- -----------------------------------------------------
-- Table `archery`.`userSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archery`.`userSession` (
  `sessionId` VARCHAR(32) NOT NULL,
  `userId` INT NOT NULL,
  `expiryDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`sessionId`),
  CONSTRAINT `userSession_user`
    FOREIGN KEY (`userId`)
    REFERENCES `archery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `userSession_user_idx` ON `archery`.`userSession` (`userId` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
